### ISSUE TITLE
File doesn't have the given chr_chr map 22_22

### ISSUE THREAD

**Issue by shiyi-pan** [changlabtw/hicmaptools#4]
Hi, I want to use hicmaptools to do some research and  meet an error.

Here is my script:

hicmaptools -in_hic inter_30.hic -pair pair.bed -output pair.tsv -random 1 &> pair.log

Here is my pair.bed:

Chr03   952484  953085  Chr03   1094107 1094708

Here is my pair.log:

Input
         hic          = inter_30.hic
         normalization= NONE
         resolution   = 10000
         query =        pair.bed
Parameters
         ner_bin     =  10
         random size =  1
Output
         output =       pair.tsv

[BEGIN]
File doesn't have the given chr_chr map 22_22

Could you give me some advise ?

**Comment by jmchangTW** [comment]
I am not sure whether your input .hic file, inter_30.hic, uses "Chr" prefix as chromosome naming or not.
Usually, I do not use "chr" i.e., 4	6686353	6990799.
Chromosome naming, Chr03, looks unusual to me.
Therefore, you might try
3 952484 953085 3 1094107 1094708
or
chr3 952484 953085 chr3 1094107 1094708

**Comment by shiyi-pan** [comment]
Thank you for your reply.
This is so strange, my reference genome is named as "Chr01" , "Chr02" and so on, but in inter_30.hic,  "Chr01" convert into "01".  I modify the pair.bed and it works well.
Thank you very much.

**Comment by alexisstutzmanlewis** [comment]
Hi @jmchangTW,

I am experiencing the same issue; however, it is not resolved when I modify my .bed file such that the chromosome naming scheme is identical. 

Here is my command:
`~/hicmaptools/src/hicmaptools -in_hic inter_30.hic -in_hic_resol 10000 -in_hic_norm VC_SQRT -random 0 -TAD tad.bed -output tad.tsv &> TAD.log`

Here is the output:

> zsh: segmentation fault  ~/hicmaptools/src/hicmaptools -in_hic  -in_hic_resol 10000 -in_hic_norm   0

And the log file:

> Input
>          hic          = inter_30.hic
>          normalization= VC_SQRT
>          resolution   = 10000
>          query =        tad.bed
> Parameters
>          ner_bin     =  10
>          random size =  0
> Output
>          output =       tad.tsv
> 
> [BEGIN]
> File doesn't have the given chr_chr map 52_52
