### ISSUE TITLE
File doesn't have the given chr_chr map not solved by renaming chromosomes

### ISSUE THREAD

**Issue by 14stutzmanav** [changlabtw/hicmaptools#5]
Hi @jmchangTW,

I am experiencing the same issue as posted [here](https://github.com/changlabtw/hicmaptools/issues/4); however, it is not resolved when I modify my .bed file such that the chromosome naming scheme is identical. 

Here is my command:
`~/hicmaptools/src/hicmaptools -in_hic inter_30.hic -in_hic_resol 10000 -in_hic_norm VC_SQRT -random 0 -TAD tad.bed -output tad.tsv &> TAD.log`

Here is the output:

> zsh: segmentation fault  ~/hicmaptools/src/hicmaptools -in_hic  -in_hic_resol 10000 -in_hic_norm   0

And the log file:

> Input
>          hic          = inter_30.hic
>          normalization= VC_SQRT
>          resolution   = 10000
>          query =        tad.bed
> Parameters
>          ner_bin     =  10
>          random size =  0
> Output
>          output =       tad.tsv
> 
> [BEGIN]
> File doesn't have the given chr_chr map 52_52

**Comment by jmchangTW** [comment]
From the log "File doesn't have the given chr_chr map 52_52", there seems a naming inconsistency between inter_30.hic and tad.bed.
Would you mind posting the first few lines of tad.bed? 
Sorry for the late reply.

**Comment by alexisstutzmanlewis** [comment]
Not a problem. Thanks for a response!

The first few lines of tad.bed are as follows (note the file is tab separated):
> 2L	22115000	22125000
> 3L	22000000	24000000

**Comment by jmchangTW** [comment]
I am wondering whether the naming of chromosome in inter_30.hic is chr2L instead of 2L.
Would you mind running "straw NONE inter_30.hic 2L: 22110000-22130000 2L: 22110000-22130000 BP 10000" first?

**Comment by alexisstutzmanlewis** [comment]
Command:
`straw NONE inter_30.hic 2L:22110000-22130000 2L:22110000-22130000 BP 10000 | head`

Output:
```
0	0	5411
0	10000	1476
10000	10000	7418
0	20000	81
10000	20000	409
20000	20000	10093
0	30000	69
10000	30000	159
20000	30000	2342
30000	30000	12223
```

**Comment by jmchangTW** [comment]
There is a problem in handling unusual chromosome names in fly (i.e., UN_CP007071V1).
I have exclusive those chromosomes when parsing .hic file.
Would you please recompile from the updated code?
