### ISSUE TITLE
Memory Corruption

### ISSUE THREAD

**Issue by 14stutzmanav** [changlabtw/hicmaptools#6]
Hi there,

I have been using hicmaptools successfully on my local device and attempted to use it in my campus's computational cluster this afternoon. When I did so, I encountered the a "memory corruption" error. I asked our IT support services what caused the issue (it works on my local machine so I thought it was related to the installation), but they said I should ask the developer of the package. Is this anything you are familiar with? Details are as follows.

Input
```
hicmaptools -in_hic inter_30.hic -TAD dm6-500000.bed -output triangles/dm6-500000-zenk-wt.tsv -random 0
```
The output is in the following file: 
[slurm-45594786.txt](https://github.com/changlabtw/hicmaptools/files/8720535/slurm-45594786.txt)

Thanks so much!
Alexis Stutzman

**Comment by jmchangTW** [comment]
Dear Alexis,

Do you re-compile HiCmapTools executable in the cluster system?
The error messages seems an incompatible running environment.
If there is still an error message after re-compile, is it possible to share inter_30.hic & dm6-500000.bed to me?
I might test it locally.

Regards!
