### ISSUE TITLE
hicmaptools running forever using Juicer mage maps

### ISSUE THREAD

**Issue by Lucas446** [changlabtw/hicmaptools#7]
Hi, 

I am using hicmaptools on mega map .hic (merged of several replicates using the mega.sh script from Juicer) as followed:

hicmaptools -in_hic ${m} -in_hic_norm ${norm} -in_hic_resol ${res} -pair ${bed} -random 1000 -output ${output_path}.tsv

Which is giving me:
```

Input
	 hic           =	/mega_map_Juicer/St10_WT_inter.hic
	 normalization =	KR
	 resolution    =	25000
	 query         =	/BEDS/234_NBPRENup_top25.bed
Parameters
	 ner_bin     =	10
	 random size =	1000
Output
	 output =	/megaSt10_WT_25000bp_KR_234_NBPRENup.tsv

[BEGIN]

```
But it doesn't go further.  However it does go complete the process if I use an individual replicate .hic file.

Something wrong with the mega map as an input for hicmaptools, 

What do you think ? 

Thanks a lot for your help, 
Best, 
Tanguy

**Comment by jmchangTW** [comment]
It is easy for me to debug step by step if I could rerun your command locally.
Therefore, is it fine for you to share St10_WT_inter.hic and 234_NBPRENup_top25.bed?

**Comment by jmchangTW** [comment]
HiCmapTools uses straw to prase input .hic file.
Therefore, I wonder whether there is a problem with the straw to read the merge .hic file.
If you have installed straw locally, please test the following command.
straw KR /mega_map_Juicer/St10_WT_inter.hic {chr_test1} {chr_test1} BP 25000

**Comment by Lucas446** [comment]
Hi, 

Thank you for replying so quickly. I can send you the files. Is it possible to send them to you directly ?

In the meantime I will try your straw command, 

Best, 
Tanguy

**Comment by Lucas446** [comment]
Hi,

I installed hicstraw for python and run the following:

```
>>> import numpy as np
>>> import hicstraw
>>> result = hicstraw.straw('observed', 'KR', 'St10_WT_inter.hic', 'X', 'X', 'BP', 25000)
File did not contain KR normalization vectors for one or both chromosomes at 25000 BP
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: vector
```

I guess the mega map script I run didn't included the KR information, do you know how to include it ?

I have no error messages when doing straw on the individual replicates, they must have the KR info

Thanks, 
Best, 
Tanguy

**Comment by jmchangTW** [comment]
After checking merge.sh, I don't think it provides a normalization function during merging. (https://github.com/aidenlab/juicer/blob/main/AWS/scripts/mega.sh)
You might try adding KR normalization for your merged .hic file.
Would you please try the addNorm function first for adding KR metrics and then rerun "result = hicstraw.straw..." ?
(https://github.com/aidenlab/juicer/wiki/AddNorm)

**Comment by Lucas446** [comment]
Thank you so much it works !
