### ISSUE TITLE
Too many random files when query contacts of million region pairs.

### ISSUE THREAD

**Issue by ttbond** [changlabtw/hicmaptools#9]
Good afternoon!

HiCmaptools is very useful! Actually, it is the most efficient tool for large scale pair contact query among those I have ever tested!
I have millions of region pairs in the input bed file, and want to get their contact using pair mode of HiCmaptools. The command ran successfully. However, I found there are milliions of random files in my workDir even after I set random parameter zero. 
These random files made my workDir unavailable...
To fix this, I annotated codes for generating random files in couple.cpp (line 189-205), and the command ran well. I'm not sure this will influence the result in tsv (with random set to zero).
If possible, I wish a parameter to prevent these random files in the further version.

Thanks for your help.
Best,
Tun Xu

**Comment by jmchangTW** [comment]
Dear Tun Xu,

Thank you for pointing out the bug.
I have revised the couple.cpp such that it will not output any random file when using -random 0.
Sorry for any inconvenience.

Regards,
Jia-Ming

**Comment by ttbond** [comment]
Thanks very much for your updates!!! I will close this issue!
